version: '3'
services:
  postgres:
    # image: postgres
    image: artifactory.global.standardchartered.com/postgres
    restart: always
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
    ports:
      - 5432:5432 
  postgres_test:
    # image: postgres
    image: artifactory.global.standardchartered.com/postgres
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
    ports:
      - 5431:5432  
